import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    'index',
    {
      type: 'category',
      label: 'Basics',
      items: [
        {
          type: 'autogenerated',
          dirName: 'basics'
        },
      ],
    }],
};

export default sidebars;
